.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH "check_nagios_latency" 1 "October, 2010" "1.0.0" "USER COMMANDS"
.SH NAME
check_nagios_latency \- checks the latency of the Nagios server
.SH SYNOPSIS
.BR "check_nagios_latency" " [-hvV?] -w warning -c critical  [-n path ] [-f cfg_file]"
.SH DESCRIPTION
.B check_nagios_latency
A Nagios plugin to check the latency of the Nagios server
.SH ARGUMENTS
.TP
.BR "-c" " threshold"
critical threshold
.TP
.BR "-w" " threshold"
warning threshold
.SH OPTIONS
.TP
.BR "-h,-?"
help message
.TP
.BR "-f" " path"
Nagios config file path
.TP
.BR "-n" " path"
nagiostats path
.TP
.BR "-v"
verbose output
.TP
.BR "-V"
version
.SH "EXIT STATUS"
check_nagios_latency returns a zero exist status if it finds no errors, 1 for warnings, 2 for a critical errors and 3 for unknown problems
.SH BUGS
Please report bugs to: Matteo Corti (matteo.corti (at) id.ethz.ch)

.SH AUTHOR
Matteo Corti (matteo.corti (at) id.ethz.ch)
See the AUTHORS file for the complete list of contributors

