#!/usr/bin/perl

use strict;
use Getopt::Long;

my $VERSION     = "1.0";

my $critical   = 0;
my $help       = '';
my $result;
my $status     = 0;
my $status_msg = '';
my $warning    = 0;

##############################################################################
# subroutines

################################
# prints the usage of the plugin
sub usage {
  my $msg = shift;

  if (defined $msg) {
    print "$msg\n";
  }

  print << "EOT";
usage:
  -c crit      critical
  -w warn      warning
  --version    version
EOT
  exit(3);
}

##############################################################################
# main
#

########################
# Command line arguments

$result = GetOptions (
    "critical=i"  => \$critical,
    "warning=i"   => \$warning,
    "help"        => \$help,
    "version"     => sub { print "check_dir version $VERSION\n"; exit 3;}
);

if (!$result) {
  usage();
}

if ($help)                { usage(); }
if ($critical <= 0)       { usage("Could not parse \"critical\""); }
if ($warning  <= 0)       { usage("Could not parse \"warning\""); }
if ($critical < $warning) { usage("\"critical\" has to be greater than \"warning\""); }

exit 3;
