#!/usr/bin/perl

use strict;
use Getopt::Long;

my $VERSION     = "1.1";

my $critical   = 0;
my $help       = '';
my $result;
my $status     = 0;
my $status_msg = '';
my $verbose    = '';
my $warning    = 0;

##############################################################################
# subroutines

################################
# prints the usage of the plugin
sub usage {
  my $msg = shift;

  if (defined $msg) {
    print "$msg\n";
  }

  print << "EOT";
usage:
  -c crit      critical
  -w warn      warning
  --version    version
  -v           verbose
EOT
  unknown();
}

#################################################
# prints an "unknown" error message (exit code 3)
sub unknown {

  my $msg = shift;

  if (defined $msg) {
    print "UNKNOWN: $msg\n";
  }

  exit(3);

}

##############################################################################
# main
#

########################
# Command line arguments

$result = GetOptions (
    "critical=i"  => \$critical,
    "warning=i"   => \$warning,
    "help"        => \$help,
    "verbose|v+"  => \$verbose,
    "version"     => sub { print "check_dir version $VERSION\n"; exit 3;}
);

if (!$result) {
  usage();
}

if ($help)                { usage(); }
if ($critical <= 0)       { usage("Could not parse \"critical\""); }
if ($warning  <= 0)       { usage("Could not parse \"warning\""); }
if ($critical < $warning) { usage("\"critical\" has to be greater than \"warning\""); }

my $command = 'netstat -a | grep ^tcp';
my $output;
my %states;

if ($verbose) {
    print "Executing: $command\n";
}

my $pid = open($output, "$command 2>&1 |") or
    die("Cannot execute $command");

while (<$output>) {
    chomp;    
    /tcp.*\s([A-Z_]+)/;
    $states{$1}++;
}

close $output or
    die("Couldn't close: $!");

# build status string
my $status;
my $total = 0;
while ( my ($state,$count) = each %states ) {
    $total += $count;
    $status = $status . ", $state = $count";
}
$status = "TOTAL = $total" . $status;

if ($total < $warning) {
  print "CONNECTIONS OK ($status)\n";
  exit 0;
} else {
  if ($total < $critical) {
    print "CONNECTIONS WARNING ($status)\n";
    exit 1;
  } else {
    print "CONNECTIONS CRITICAL ($status)\n";
    exit 2;
  }
}
