---
abstract: ~
author:
  - 'Matteo Corti <matteo.corti@id.ethz.ch>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: check_bandwidth
no_index:
  directory:
    - inc
requires:
  Carp: 0
  English: 0
  File::Slurp: 0
  Getopt::Long: 0
  Monitoring::Plugin: 0
  Monitoring::Plugin::Threshold: 0
  Net::DNS::Resolver: 0
  perl: 5.8.0
  version: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.9.6
