#!/bin/bash

VOS=/usr/sbin/vos
VERSION=0.9

usage() {

    if [ -n "$1" ] ; then
        echo "Error: $1" 1>&2
    fi
    

    echo
    echo "Usage: check_afs_offline_volumes -H server [-hvw?]"
    echo
    echo "   -h, -? this help message"
    echo "   -H     server"
    echo "   -v     verbose output"
    echo "   -V     version"
    echo
    echo "Report bugs to: Matteo Corti <matteo.corti@id.ethz.ch>"
    echo

    exit 3

}

# process command line options

while getopts "vh?H:V" opt; do
    case $opt in
        h | \? ) usage ; exit 3; ;;
        v )      VERBOSE=1;      ;;
        V )      echo "check_afs_offline_volumes version ${VERSION}"; exit 3; ;;
        H )      SERVER=$OPTARG; ;;
    esac
done
shift $(($OPTIND - 1))

# sanity checks
if [ -z "${SERVER}" ] ; then
    usage "No server specified"
fi

OFFLINE=`${VOS} listvol ${SERVER} -noauth | grep Off-line | wc -l`

STATUS="|VOLUMES=${OFFLINE};;;;";
if [ ${OFFLINE} -ge 1 ] ; then
    echo "AFS OFFLINE CRITICAL${STATUS}";
    exit 2
else
    echo "AFS OFFLINE OK${STATUS}";
    exit 0
fi
