#!perl

# check_homes is Nagios plugin to check the availability of home directories
#
# See  the INSTALL file for installation instructions
#
# Copyright (c) 2007, ETH Zurich.
#
# This module is free software; you can redistribute it and/or modify it
# under the terms of GNU general public license (gpl) version 3.
# See the LICENSE file for details.
#
# RCS information
# enable substitution with:
#   $ svn propset svn:keywords "Id Revision HeadURL Source Date"
#
#   $Id$
#   $Revision$
#   $HeadURL$
#   $Date$

use 5.008;
use strict;
use warnings;
use Carp;

use version; our $VERSION = '0.1.4';

use English qw(-no_match_vars);
use Getopt::Long;
use List::MoreUtils qw(any);
use List::Util qw(first);
use Nagios::Plugin::Threshold;
use Nagios::Plugin;
use Pod::Usage qw(pod2usage);

# IMPORTANT: Nagios plugins could be executed using embedded perl in this case
#            the main routine would be executed as a subroutine and all the
#            declared subroutines would therefore be inner subroutines
#            This will cause all the global lexical variables not to stay shared
#            in the subroutines!
#
# All variables are therefore declared as package variables...
#
use vars qw(
  @errors
  $help
  $home_checks
  $plugin
  $threshold
  $tmp
  $verbosity
);

##############################################################################
# subroutines

##############################################################################
# Usage     : verbose("some message string", $optional_verbosity_level);
# Purpose   : write a message if the verbosity level is high enough
# Returns   : n/a
# Arguments : message : message string
#             level   : options verbosity level
# Throws    : n/a
# Comments  : n/a
# See also  : n/a
sub verbose {

    # arguments
    my $message = shift;
    my $level   = shift;

    if ( !defined $message ) {
        $plugin->nagios_exit( UNKNOWN,
            q{Internal error: not enough parameters for 'verbose'} );
    }

    if ( !defined $level ) {
        $level = 0;
    }

    if ( $level < $verbosity ) {
        print $message;
    }

    return;

}

##############################################################################
# Usage     : whoami()
# Purpose   : retrieve the user runnging the process
# Returns   : username
# Arguments : n/a
# Throws    : n/a
# Comments  : n/a
# See also  : n/a
sub whoami {
    my $output;
    my $pid = open $output, q{-|}, 'whoami'
      or
      $plugin->nagios_exit( UNKNOWN, "Cannot determine the user: $OS_ERROR" );
    while (<$output>) {
        chomp;
        return $_;
    }
    $plugin->nagios_exit( UNKNOWN, 'Cannot determine the user' );
    return;
}

##############################################################################
# Usage     : check_user()
# Purpose   : check a users' home
# Returns   : n/a
# Arguments : user : username
# Throws    : n/a
# Comments  : n/a
# See also  : n/a
sub check_user {

    my $user = shift;
    my $home = "/nas/$user";

    verbose "checking $user's home: $home\n", 1;

    my $ls;
    my $command = "ls -d $home 2>&1 ";
    open $ls, q{-|}, $command
      or
      $plugin->nagios_exit( UNKNOWN, "Cannot execute \"$command\": $OS_ERROR" );

    while (<$ls>) {
        chomp;
        if ( $_ ne $home ) {
            push @errors, $user;
        }
    }

    return;

}

##############################################################################
# main
#

################
# initialization
$home_checks = 1;
$help        = q{};
$verbosity   = 0;
$tmp         = '/tmp/check_homes_status-' . whoami();
$plugin      = Nagios::Plugin->new( shortname => 'CHECK_HOMES' );
$threshold   = Nagios::Plugin::Threshold->set_thresholds(
    warning  => 0,
    critical => 0,
);

########################
# Command line arguments

Getopt::Long::Configure(qw{bundling });
my $result = GetOptions(
    'help|h|?'   => \$help,
    'checks|c=i' => \$home_checks,
    'verbose|v+' => \$verbosity,
    'version|V'  => sub { print "check_updates version $VERSION\n"; exit 3; }
);

if ( !$result || $help ) {
    pod2usage();
}

##############################################################################
# get the user list

my @users;
my $list;
my $filename = '/home/n/conf/studmigr_1.txt';

open $list, q{<}, $filename
  or $plugin->nagios_exit( UNKNOWN, "Cannot open $filename: $OS_ERROR" );

while (<$list>) {
    s/\ .*//mx;
    chomp;
    push @users, $_;
}

close $list
  or $plugin->nagios_exit( UNKNOWN, "Cannot close $filename: $OS_ERROR" );

my $users_number = @users;

verbose "Retrieved $users_number users\n";

verbose "Selecting $home_checks random"
  . ( ( $home_checks > 0 ) ? 'users' : 'user' ) . "\n";

srand;

my $i = 0;
my @to_check;

while ( $i < $home_checks ) {

    my $index = int rand $users_number;

    if ( any { /$users[$index]/mx } @to_check ) {
        redo;
    }

    verbose "  $users[$index]\n", 1;
    push @to_check, $users[$index];

    $i++;

}

my $file;

if ( -f $tmp ) {

    verbose "Adding problematic users from last run\n";

    open $file, q{<}, $tmp
      or $plugin->nagios_exit( UNKNOWN, "Cannot open $tmp: $OS_ERROR" );

    while (<$file>) {
        chomp;
        verbose "  $_\n", 1;
        push @to_check, $_;
    }

    close $file
      or $plugin->nagios_exit( UNKNOWN, "Cannot close $tmp: $OS_ERROR" );

}

for my $user (@to_check) {
    check_user($user);
}

$plugin->add_perfdata(
    label     => 'errors',
    value     => scalar @errors,
    uom       => q{},
    threshold => $threshold,
);

if (@errors) {
    my $error_string;

    # write the temporary error file
    my $file;
    open $file, q{>}, $tmp
      or $plugin->nagios_exit( WARNING, "Error opening $tmp: $OS_ERROR" );

    for my $user (@errors) {
        print {$file} "$user\n";
    }

    close $file
      or $plugin->nagios_exit( WARNING, "Error closing $tmp: $OS_ERROR" );

    # generate error message

    for my $user (@errors) {
        if ( defined $error_string ) {
            $error_string = "$error_string, /nas/$user";
        }
        else {
            $error_string = "/nas/$user";
        }
    }
    $plugin->nagios_exit( CRITICAL, "Error accessing $error_string" );
}
else {
    $plugin->nagios_exit( OK,
        "Checked $home_checks " . ( ( $home_checks > 1 ) ? 'homes' : 'home' ) );
}

1;

__END__

=pod

=head1 NAME

C<check_updates> - a Nagios plugin to check if RedHat or Fedora system
is up-to-date

=head1 DESCRIPTION

check_updates is a Nagios plugin to check if RedHat or Fedora system
is up-to-date

=head1 VERSION

Version 0.9.7

=head1 SYNOPSIS

 check_updates [--help] [--verbose] [--version]

 Options    
  --help,-h,-?                  this help message
  --verbose,-v                  verbose output
  --version,-V                  print version

=head1 REQUIRED ARGUMENTS


=head1 OPTIONS

  --help,-h,-?                  this help message

  --version,-V                  print version

  --verbose,-v                  verbose output

=head1 EXAMPLE

 check_updates

check_updates checks if the system is up-to-date

=head1 DIAGNOSTICS

You can specify multiple --verbose options to increase the program
verbosity.

=head1 EXIT STATUS

0 if OK, 1 in case of a warning, 2 in case of a critical status and 3
in case of an unkown problem

=head1 DEPENDENCIES

check_updates depends on

=over 4

=item * Carp

=item * English

=item * Getopt::Long

=item * List::MoreUtils

=item * List::Util

=item * Nagios::Plugin

=item * Nagios::Plugin::Threshold

=item * Number::Format

=item * POSIX

=item * Pod::Usage

=item * version

=back

=head1 CONFIGURATION

=head1 INCOMPATIBILITIES

None reported.

=head1 SEE ALSO

Nagios documentation

=head1 BUGS AND LIMITATIONS

No bugs have been reported.

Please report any bugs or feature requests to matteo.corti@id.ethz.ch,
or through the web interface at
https://svn.id.ethz.ch/trac/bd_webhosting/newticket

=head1 AUTHOR

Matteo Corti <matteo.corti@id.ethz.ch>

=head1 LICENSE AND COPYRIGHT

Copyright (c) 2007, ETH Zurich.

This module is free software; you can redistribute it and/or modify it
under the terms of GNU general public license (gpl) version 3.
See the LICENSE file for details.

=head1 DISCLAIMER OF WARRANTY

BECAUSE THIS SOFTWARE IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY
FOR THE SOFTWARE, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT
WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER
PARTIES PROVIDE THE SOFTWARE "AS IS" WITHOUT WARRANTY OF ANY KIND,
EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE
SOFTWARE IS WITH YOU. SHOULD THE SOFTWARE PROVE DEFECTIVE, YOU ASSUME
THE COST OF ALL NECESSARY SERVICING, REPAIR, OR CORRECTION.

IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR
REDISTRIBUTE THE SOFTWARE AS PERMITTED BY THE ABOVE LICENCE, BE LIABLE
TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL, OR
CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE
SOFTWARE (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING
RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A
FAILURE OF THE SOFTWARE TO OPERATE WITH ANY OTHER SOFTWARE), EVEN IF
SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
DAMAGES.

=head1 ACKNOWLEDGMENTS

