#!/usr/bin/perl

# RCS information (required by Perl::Critic)
#   $Id$
#   $Revision$
#   $HeadURL$
#   $Date$

use strict;
use warnings;

use Getopt::Long;
use English '-no_match_vars';
use version; our $VERSION='1.0';

my $hostname   = q{};
my $vos        = '/usr/sbin/vos';
my $verbose    = q{};
my $help       = q{};
my $warning    = 0;
my $critical   = 0;
my $result     = 0;
my $status     = 0;
my $status_msg = q{};


##############################################################################

################################
# prints the usage of the plugin
sub usage {

    my $msg = shift;

    if (defined $msg) {
        print "$msg\n";
    }

  print << "EOT";
usage:
  -H,--hostname=server    server
  --vos=path              vos executable location
  --version               version
  -v                      verbose
EOT
  
    unknown();

    return;

}

#################################################
# prints an "unknown" error message (exit code 3)
sub unknown {

  my $msg = shift;

  if (defined $msg) {
    print "UNKNOWN: $msg\n";
  }

  exit 3;

}

##############################################################################

Getopt::Long::Configure ('bundling', 'no_ignorecase');

########################
# Command line arguments

$result = GetOptions ('hostname|H=s' => \$hostname,
                      'help|h'       => \$help,
                      'verbose|v+'   => \$verbose,
                      'vos'          => \$vos,
                      'version'      => sub { print "check_dir version $VERSION\n"; exit 3;} );

if (!$result) {
  usage();
}

if ($help)                { usage(); }
if (!$hostname)           { usage(); }

# execute vos listvol
my $OUT_FH;
my $pid = open
    $OUT_FH,
    '<',
    "$vos listvol $hostname 2>/dev/null | grep 'Could not attach' |";

while (<$OUT_FH>) {
  chomp;
  $status_msg = $status_msg . $_;
  $status     = 2;
}

close $OUT_FH or croak "Error: cannot close filehandle on command: $OS_ERROR";

if ($status == 0) {
  print "AFS_VOL OK\n";
  exit 0;
} else {
  if ($status == 1) {
    print "AFS_VOL WARNING - $status_msg\n";
  } else {
    print "AFS_VOL CRITICAL - $status_msg\n";
  }
  exit $status;
}
